apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: db
    template:
        metadata:
            labels:
                component: db
        spec:
            volumes:
                - name: db-storage
                  persistentVolumeClaim:
                      claimName: db-persistent-volume-claim
            containers:
                - name: blackblade-db
                  image: brandonwade/blackblade-db:latest
                  args:
                      - '--sql-mode='
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: db-storage
                        mountPath: /mnt/data
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysqlrootpassword
                                key: MYSQL_ROOT_PASSWORD
                      - name: MYSQL_DATABASE
                        value: blackblade
                      - name: MYSQL_USER
                        value: blackblade
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysqlpassword
                                key: MYSQL_PASSWORD
            imagePullSecrets:
                - name: regcred
